using System.Text;
using System.Text.RegularExpressions;
using DocuGenious.Core.Configuration;
using DocuGenious.Core.Interfaces;
using DocuGenious.Core.Models;
using Microsoft.Extensions.Logging;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace DocuGenious.Integration.Pdf;

public class PdfService : IPdfService
{
    private readonly OutputSettings _settings;
    private readonly ILogger<PdfService> _logger;

    // Brand colours
    private const string PrimaryColor  = "#1E3A5F";
    private const string AccentColor   = "#2E86AB";
    private const string LightGray     = "#F5F7FA";
    private const string DarkGray      = "#4A4A4A";
    private const string CodeBg        = "#F0F4F8";
    private const string CodeFg        = "#2C3E50";
    private const string TerminalBg    = "#1E1E1E";
    private const string TerminalFg    = "#D4D4D4";
    private const string WarnColor     = "#E74C3C";

    public PdfService(AppSettings settings, ILogger<PdfService> logger)
    {
        _settings = settings.Output;
        _logger   = logger;
        QuestPDF.Settings.License = LicenseType.Community;
    }

    // ─── Public entry ─────────────────────────────────────────────────────────────

    public Task<string> GeneratePdfAsync(AnalysisResult result, string outputFileName)
    {
        Directory.CreateDirectory(Path.GetFullPath(_settings.PdfDirectory));

        var sanitized = string.Concat(outputFileName.Split(Path.GetInvalidFileNameChars()));
        if (!sanitized.EndsWith(".pdf", StringComparison.OrdinalIgnoreCase))
            sanitized += ".pdf";

        var outputPath = Path.Combine(Path.GetFullPath(_settings.PdfDirectory), sanitized);
        _logger.LogInformation("Generating PDF at {Path}", outputPath);

        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontFamily("Arial").FontSize(10).FontColor(DarkGray));

                page.Header().Element(ComposeHeader);
                page.Content().Element(c => ComposeContent(c, result));
                page.Footer().Element(ComposeFooter);
            });
        }).GeneratePdf(outputPath);

        _logger.LogInformation("PDF generated: {Path}", outputPath);
        return Task.FromResult(outputPath);
    }

    // ─── Header / Footer ─────────────────────────────────────────────────────────

    private static void ComposeHeader(IContainer container)
    {
        container.Column(col =>
        {
            col.Item().Background(PrimaryColor).Padding(16).Row(row =>
            {
                row.RelativeItem().Column(inner =>
                {
                    inner.Item().Text("Docu-Genius").FontSize(22).Bold().FontColor(Colors.White);
                    inner.Item().Text("AI-Powered Documentation").FontSize(11).Italic().FontColor("#B0C4D8");
                });
                row.ConstantItem(160).AlignRight().Column(inner =>
                    inner.Item().Text(DateTime.UtcNow.ToString("MMMM dd, yyyy")).FontSize(9).FontColor("#B0C4D8"));
            });
            col.Item().Background(AccentColor).Height(3);
        });
    }

    private static void ComposeFooter(IContainer container)
    {
        container.BorderTop(1).BorderColor(Colors.Grey.Lighten2).PaddingTop(6).Row(row =>
        {
            row.RelativeItem()
                .Text("Generated by Docu-Genius · Powered by Google Gemini AI")
                .FontSize(8).FontColor(Colors.Grey.Medium);

            row.ConstantItem(80).AlignRight().Text(text =>
            {
                text.Span("Page ").FontSize(8).FontColor(Colors.Grey.Medium);
                text.CurrentPageNumber().FontSize(8).FontColor(Colors.Grey.Medium);
                text.Span(" of ").FontSize(8).FontColor(Colors.Grey.Medium);
                text.TotalPages().FontSize(8).FontColor(Colors.Grey.Medium);
            });
        });
    }

    // ─── Main content ─────────────────────────────────────────────────────────────

    private static void ComposeContent(IContainer container, AnalysisResult result)
    {
        container.PaddingTop(16).Column(col =>
        {
            col.Spacing(22);

            col.Item().Element(c => ComposeCoverBlock(c, result));

            if (!string.IsNullOrWhiteSpace(result.ExecutiveSummary))
                col.Item().Element(c => ComposeSection(c, "Executive Summary", result.ExecutiveSummary));

            if (!string.IsNullOrWhiteSpace(result.TechnicalOverview))
                col.Item().Element(c => ComposeSection(c, "Technical Overview", result.TechnicalOverview));

            if (!string.IsNullOrWhiteSpace(result.ArchitectureDescription))
                col.Item().Element(c => ComposeSection(c, "Architecture Overview", result.ArchitectureDescription));

            if (result.Features.Count > 0)
                col.Item().Element(c => ComposeFeaturesSection(c, result.Features));

            if (!string.IsNullOrWhiteSpace(result.UserGuide))
                col.Item().Element(c => ComposeSection(c, "User Guide", result.UserGuide));

            if (!string.IsNullOrWhiteSpace(result.SetupInstructions))
                col.Item().Element(c => ComposeSection(c, "Setup Instructions", result.SetupInstructions));

            if (!string.IsNullOrWhiteSpace(result.ConfigurationGuide))
                col.Item().Element(c => ComposeSection(c, "Configuration Guide", result.ConfigurationGuide));

            if (result.ApiEndpoints.Count > 0)
                col.Item().Element(c => ComposeApiSection(c, result.ApiEndpoints));

            if (result.Dependencies.Count > 0)
                col.Item().Element(c => ComposeListSection(c, "Dependencies", result.Dependencies));

            if (result.Recommendations.Count > 0)
                col.Item().Element(c => ComposeListSection(c, "Recommendations", result.Recommendations, AccentColor));

            if (result.KnownIssues.Count > 0)
                col.Item().Element(c => ComposeListSection(c, "Known Issues", result.KnownIssues, WarnColor));
        });
    }

    // ─── Cover block ─────────────────────────────────────────────────────────────

    private static void ComposeCoverBlock(IContainer container, AnalysisResult result)
    {
        container.Background(LightGray).Padding(20).Column(col =>
        {
            col.Item().Text(GetDocumentTitle(result.DocumentationType))
                .FontSize(20).Bold().FontColor(PrimaryColor);
            col.Item().PaddingTop(6).Text(result.SourceInfo)
                .FontSize(10).Italic().FontColor(Colors.Grey.Darken1);
            col.Item().PaddingTop(4).Text($"Generated: {result.GeneratedAt:yyyy-MM-dd HH:mm} UTC")
                .FontSize(9).FontColor(Colors.Grey.Medium);
        });
    }

    // ─── Section with markdown body ───────────────────────────────────────────────

    private static void ComposeSection(IContainer container, string title, string content)
    {
        container.Column(col =>
        {
            col.Item().Element(c => ComposeSectionHeading(c, title));
            col.Item().PaddingTop(10).Element(c => RenderMarkdown(c, content));
        });
    }

    // ─── Features section ────────────────────────────────────────────────────────

    private static void ComposeFeaturesSection(IContainer container, List<Feature> features)
    {
        container.Column(col =>
        {
            col.Item().Element(c => ComposeSectionHeading(c, "Features"));
            col.Item().PaddingTop(10).Column(inner =>
            {
                inner.Spacing(10);
                foreach (var f in features)
                {
                    inner.Item().Background(LightGray).Padding(12).Column(fc =>
                    {
                        fc.Item().Text(f.Name).Bold().FontSize(11).FontColor(PrimaryColor);

                        if (!string.IsNullOrWhiteSpace(f.Description))
                            fc.Item().PaddingTop(4).Element(c => RenderMarkdown(c, f.Description));

                        if (!string.IsNullOrWhiteSpace(f.UsageExample))
                        {
                            fc.Item().PaddingTop(6)
                                .Text("Example").Bold().FontSize(9).FontColor(AccentColor);
                            fc.Item().PaddingTop(2).Background(CodeBg).Padding(8)
                                .Text(f.UsageExample)
                                .FontFamily("Courier New").FontSize(9).FontColor(CodeFg);
                        }
                    });
                }
            });
        });
    }

    // ─── API section ─────────────────────────────────────────────────────────────

    private static void ComposeApiSection(IContainer container, List<ApiEndpoint> endpoints)
    {
        container.Column(col =>
        {
            col.Item().Element(c => ComposeSectionHeading(c, "API Endpoints"));
            col.Item().PaddingTop(10).Column(inner =>
            {
                inner.Spacing(8);

                // Header row
                inner.Item().Background(PrimaryColor).Padding(8).Row(row =>
                {
                    row.ConstantItem(55).Text("Method").FontSize(9).Bold().FontColor(Colors.White);
                    row.RelativeItem(2).Text("Path").FontSize(9).Bold().FontColor(Colors.White);
                    row.RelativeItem(3).Text("Description").FontSize(9).Bold().FontColor(Colors.White);
                });

                foreach (var ep in endpoints)
                {
                    inner.Item().BorderBottom(1).BorderColor(Colors.Grey.Lighten2).Padding(6).Row(row =>
                    {
                        row.ConstantItem(55)
                            .Background(GetMethodColor(ep.Method)).Padding(4).AlignCenter()
                            .Text(ep.Method.ToUpper()).FontSize(8).Bold().FontColor(Colors.White);

                        row.RelativeItem(2).PaddingLeft(6)
                            .Text(ep.Path).FontFamily("Courier New").FontSize(9);

                        row.RelativeItem(3).PaddingLeft(6)
                            .Text(ep.Description).FontSize(9).LineHeight(1.3f);
                    });

                    if (!string.IsNullOrWhiteSpace(ep.RequestBody) || !string.IsNullOrWhiteSpace(ep.ResponseBody))
                    {
                        inner.Item().PaddingLeft(8).PaddingBottom(8).Column(detail =>
                        {
                            if (!string.IsNullOrWhiteSpace(ep.RequestBody))
                            {
                                detail.Item().PaddingBottom(3)
                                    .Text("Request Body").FontSize(8).Bold().FontColor(AccentColor);
                                detail.Item().Element(c => RenderTerminalBlock(c, ep.RequestBody));
                            }
                            if (!string.IsNullOrWhiteSpace(ep.ResponseBody))
                            {
                                detail.Item().PaddingTop(8).PaddingBottom(3)
                                    .Text("Response Body").FontSize(8).Bold().FontColor(AccentColor);
                                detail.Item().Element(c => RenderTerminalBlock(c, ep.ResponseBody));
                            }
                        });
                    }
                }
            });
        });
    }

    // ─── List section ────────────────────────────────────────────────────────────

    private static void ComposeListSection(
        IContainer container, string title, List<string> items, string? bulletColor = null)
    {
        container.Column(col =>
        {
            col.Item().Element(c => ComposeSectionHeading(c, title));
            col.Item().PaddingTop(10).Column(inner =>
            {
                inner.Spacing(5);
                foreach (var item in items)
                {
                    inner.Item().Row(row =>
                    {
                        row.ConstantItem(14).Text("•").FontSize(12).FontColor(bulletColor ?? PrimaryColor);
                        row.RelativeItem().PaddingLeft(4).Element(c => RenderInlineText(c, item, 10));
                    });
                }
            });
        });
    }

    // ─── Section heading ─────────────────────────────────────────────────────────

    private static void ComposeSectionHeading(IContainer container, string title)
    {
        container.Column(col =>
        {
            col.Item().Text(title).FontSize(14).Bold().FontColor(PrimaryColor);
            col.Item().PaddingTop(2).Background(AccentColor).Height(2);
        });
    }

    // =========================================================================
    // Markdown renderer
    // =========================================================================

    /// <summary>
    /// Parses markdown content into visual blocks and renders each one using QuestPDF.
    /// Handles: headings (#/##/###), bullet lists, numbered lists, code blocks,
    /// horizontal rules, blank-line-separated paragraphs, and inline bold/italic/code.
    /// </summary>
    private static void RenderMarkdown(IContainer container, string raw)
    {
        // If the field content is actual valid JSON (raw-fallback path), convert it to
        // readable markdown prose instead of rendering it as a monochrome code block.
        var trimmed = raw.Trim();
        if (IsActualJson(trimmed))
        {
            raw = ConvertJsonToMarkdown(trimmed);
        }

        var blocks = ParseMarkdownBlocks(NormalizeInlineNumberedLists(raw));

        container.Column(col =>
        {
            col.Spacing(5);

            foreach (var block in blocks)
            {
                switch (block.Type)
                {
                    case MdBlockType.H1:
                        col.Item().PaddingTop(8)
                            .Text(block.Text).FontSize(14).Bold().FontColor(PrimaryColor);
                        col.Item().Background(AccentColor).Height(1);
                        break;

                    case MdBlockType.H2:
                        col.Item().PaddingTop(6)
                            .Text(block.Text).FontSize(12).Bold().FontColor(PrimaryColor);
                        break;

                    case MdBlockType.H3:
                        col.Item().PaddingTop(4)
                            .Text(block.Text).FontSize(11).Bold().FontColor(AccentColor);
                        break;

                    case MdBlockType.H4:
                        col.Item().PaddingTop(2)
                            .Text(block.Text).FontSize(10).Bold();
                        break;

                    case MdBlockType.HRule:
                        col.Item().PaddingVertical(4).Background(Colors.Grey.Lighten2).Height(1);
                        break;

                    case MdBlockType.CodeBlock:
                        col.Item().Background(CodeBg).Padding(8)
                            .Text(block.Text)
                            .FontFamily("Courier New").FontSize(8.5f).FontColor(CodeFg).LineHeight(1.4f);
                        break;

                    case MdBlockType.Bullet:
                        col.Item().PaddingBottom(3).Row(row =>
                        {
                            if (block.Indent > 0)
                                row.ConstantItem(block.Indent * 14);

                            row.ConstantItem(14)
                                .AlignTop()
                                .Text("•").FontSize(11).FontColor(PrimaryColor);

                            row.RelativeItem().PaddingLeft(4)
                                .Element(c => RenderInlineText(c, block.Text, 10));
                        });
                        break;

                    case MdBlockType.Numbered:
                        col.Item().PaddingBottom(4).Row(row =>
                        {
                            if (block.Indent > 0)
                                row.ConstantItem(block.Indent * 14);

                            row.ConstantItem(26)
                                .AlignTop()
                                .Text($"{block.Number}.")
                                .FontSize(10).Bold().FontColor(PrimaryColor);

                            row.RelativeItem().PaddingLeft(4)
                                .Element(c => RenderInlineText(c, block.Text, 10));
                        });
                        break;

                    case MdBlockType.BlockQuote:
                        col.Item().BorderLeft(3).BorderColor(AccentColor)
                            .PaddingLeft(10).PaddingVertical(4)
                            .Element(c => RenderInlineText(c, block.Text, 10));
                        break;

                    case MdBlockType.Paragraph:
                    default:
                        col.Item().Element(c => RenderInlineText(c, block.Text, 10));
                        break;
                }
            }
        });
    }

    // ─── Inline text renderer (bold / italic / inline-code) ───────────────────────

    /// <summary>
    /// Renders a single line of text with inline markdown:
    /// **bold**, *italic*, __bold__, _italic_, `code`
    /// </summary>
    private static void RenderInlineText(IContainer container, string text, float fontSize)
    {
        var spans = ParseInlineSpans(text);

        if (spans.All(s => !s.Bold && !s.Italic && !s.Code))
        {
            // Fast path — no inline formatting
            container.Text(text).FontSize(fontSize).LineHeight(1.5f);
            return;
        }

        container.Text(t =>
        {
            t.DefaultTextStyle(s => s.FontSize(fontSize).LineHeight(1.5f));

            foreach (var span in spans)
            {
                var s = t.Span(span.Text);

                if (span.Code)
                {
                    s.FontFamily("Courier New")
                     .FontSize(fontSize - 0.5f)
                     .BackgroundColor(CodeBg)
                     .FontColor(CodeFg);
                }
                else
                {
                    if (span.Bold)   s.Bold();
                    if (span.Italic) s.Italic();
                }
            }
        });
    }

    // =========================================================================
    // Inline numbered-list normaliser
    // =========================================================================

    private static readonly Regex ListMarkerRx =
        new(@"\d+[).]\s+", RegexOptions.Compiled);

    private static readonly Regex ItemOneRx =
        new(@"(^|\s)1[).]\s", RegexOptions.Compiled);
    private static readonly Regex ItemTwoRx =
        new(@"(^|\s)2[).]\s", RegexOptions.Compiled);

    private static string NormalizeInlineNumberedLists(string raw)
    {
        var sb = new StringBuilder();

        foreach (var rawLine in raw.Replace("\r\n", "\n").Split('\n'))
        {
            var line = rawLine.TrimEnd();

            if (!ItemOneRx.IsMatch(line) || !ItemTwoRx.IsMatch(line))
            {
                sb.AppendLine(line);
                continue;
            }

            var markerMatches = ListMarkerRx.Matches(line)
                .Cast<Match>()
                .Where(m => m.Index == 0 || char.IsWhiteSpace(line[m.Index - 1]))
                .ToList();

            if (markerMatches.Count < 2)
            {
                sb.AppendLine(line);
                continue;
            }

            var intro = line[..markerMatches[0].Index].TrimEnd().TrimEnd(':').Trim();
            if (!string.IsNullOrWhiteSpace(intro))
                sb.AppendLine(intro + ":");

            for (int i = 0; i < markerMatches.Count; i++)
            {
                var m         = markerMatches[i];
                var numStr    = Regex.Match(m.Value, @"^\d+").Value;
                int textStart = m.Index + m.Length;
                int textEnd   = i + 1 < markerMatches.Count
                    ? markerMatches[i + 1].Index
                    : line.Length;

                while (textEnd > textStart && char.IsWhiteSpace(line[textEnd - 1]))
                    textEnd--;

                var text = line[textStart..textEnd].Trim();
                if (!string.IsNullOrWhiteSpace(text))
                    sb.AppendLine($"{numStr}. {text}");
            }
        }

        return sb.ToString();
    }

    // =========================================================================
    // Block parser
    // =========================================================================

    private enum MdBlockType
    { H1, H2, H3, H4, Paragraph, Bullet, Numbered, CodeBlock, HRule, BlockQuote }

    private record MdBlock(MdBlockType Type, string Text, int Number = 0, int Indent = 0);

    private static readonly Regex NumberedListRx =
        new(@"^(\s*)(\d+)[).]\s+(.+)$", RegexOptions.Compiled);

    private static readonly Regex BulletListRx =
        new(@"^(\s*)[-*+]\s+(.+)$", RegexOptions.Compiled);

    private static List<MdBlock> ParseMarkdownBlocks(string raw)
    {
        var blocks  = new List<MdBlock>();
        var lines   = raw.Replace("\r\n", "\n").Split('\n');
        var paraBuffer = new StringBuilder();
        bool inCode = false;
        var  codeBuf = new StringBuilder();

        void FlushParagraph()
        {
            var para = paraBuffer.ToString().Trim();
            if (para.Length > 0)
                blocks.Add(new MdBlock(MdBlockType.Paragraph, para));
            paraBuffer.Clear();
        }

        foreach (var rawLine in lines)
        {
            var line = rawLine.TrimEnd();

            if (line.TrimStart().StartsWith("```"))
            {
                if (!inCode)
                {
                    FlushParagraph();
                    inCode = true;
                    codeBuf.Clear();
                }
                else
                {
                    blocks.Add(new MdBlock(MdBlockType.CodeBlock, codeBuf.ToString().TrimEnd()));
                    inCode = false;
                }
                continue;
            }

            if (inCode)
            {
                codeBuf.AppendLine(line);
                continue;
            }

            if (Regex.IsMatch(line, @"^(\s*[-*_]){3,}\s*$"))
            {
                FlushParagraph();
                blocks.Add(new MdBlock(MdBlockType.HRule, string.Empty));
                continue;
            }

            var headingMatch = Regex.Match(line, @"^(#{1,4})\s+(.+)");
            if (headingMatch.Success)
            {
                FlushParagraph();
                var level = headingMatch.Groups[1].Value.Length;
                var text  = headingMatch.Groups[2].Value.Trim();
                var type  = level switch { 1 => MdBlockType.H1, 2 => MdBlockType.H2,
                                           3 => MdBlockType.H3, _ => MdBlockType.H4 };
                blocks.Add(new MdBlock(type, text));
                continue;
            }

            if (line.TrimStart().StartsWith("> "))
            {
                FlushParagraph();
                blocks.Add(new MdBlock(MdBlockType.BlockQuote,
                    line.TrimStart().Substring(2).Trim()));
                continue;
            }

            var numMatch = NumberedListRx.Match(line);
            if (numMatch.Success)
            {
                FlushParagraph();
                int indent = numMatch.Groups[1].Value.Length / 2;
                int num    = int.Parse(numMatch.Groups[2].Value);
                string txt = numMatch.Groups[3].Value;
                blocks.Add(new MdBlock(MdBlockType.Numbered, txt, num, indent));
                continue;
            }

            var bulletMatch = BulletListRx.Match(line);
            if (bulletMatch.Success)
            {
                FlushParagraph();
                int indent = bulletMatch.Groups[1].Value.Length / 2;
                string txt = bulletMatch.Groups[2].Value;
                blocks.Add(new MdBlock(MdBlockType.Bullet, txt, 0, indent));
                continue;
            }

            if (string.IsNullOrWhiteSpace(line))
            {
                FlushParagraph();
                continue;
            }

            if (paraBuffer.Length > 0)
                paraBuffer.Append(' ');
            paraBuffer.Append(line.Trim());
        }

        if (inCode && codeBuf.Length > 0)
            blocks.Add(new MdBlock(MdBlockType.CodeBlock, codeBuf.ToString().TrimEnd()));

        FlushParagraph();

        return blocks;
    }

    // =========================================================================
    // Inline span parser
    // =========================================================================

    private record InlineSpan(string Text, bool Bold = false, bool Italic = false, bool Code = false);

    private static List<InlineSpan> ParseInlineSpans(string text)
    {
        var spans  = new List<InlineSpan>();
        var remain = text;

        var rx = new Regex(@"(`[^`]+`|\*\*[^*]+\*\*|__[^_]+__|(?<!\*)\*(?!\*)[^*]+(?<!\*)\*(?!\*)|(?<!_)_(?!_)[^_]+(?<!_)_(?!_))");

        int pos = 0;
        foreach (Match m in rx.Matches(text))
        {
            if (m.Index > pos)
                spans.Add(new InlineSpan(text[pos..m.Index]));

            var raw = m.Value;

            if (raw.StartsWith("`") && raw.EndsWith("`"))
                spans.Add(new InlineSpan(raw[1..^1], Code: true));
            else if (raw.StartsWith("**") || raw.StartsWith("__"))
                spans.Add(new InlineSpan(raw[2..^2], Bold: true));
            else
                spans.Add(new InlineSpan(raw[1..^1], Italic: true));

            pos = m.Index + m.Length;
        }

        if (pos < text.Length)
            spans.Add(new InlineSpan(text[pos..]));

        return spans.Where(s => s.Text.Length > 0).ToList();
    }

    // ─── Terminal code block ──────────────────────────────────────────────────────

    private static void RenderTerminalBlock(IContainer container, string content)
    {
        var formatted = PrettyPrintJson(content.Trim());

        container
            .Background(TerminalBg)
            .Border(1).BorderColor("#3C3C3C")
            .Padding(10)
            .Column(col =>
            {
                col.Spacing(0);

                foreach (var line in formatted.Split('\n'))
                {
                    col.Item()
                        .Text(line.TrimEnd())
                        .FontFamily("Courier New")
                        .FontSize(8.5f)
                        .FontColor(TerminalFg)
                        .LineHeight(1.5f);
                }
            });
    }

    private static string PrettyPrintJson(string raw)
    {
        var trimmed = raw.Trim();

        if (!trimmed.StartsWith("{") && !trimmed.StartsWith("["))
            return trimmed;

        var pretty = TryParseJson(trimmed);
        if (pretty != null) return pretty;

        var cleaned = trimmed
            .Replace("'", "\"")
            .Replace(",\n}", "\n}").Replace(",\n]", "\n]")
            .Replace(", }", " }").Replace(", ]", " ]");

        pretty = TryParseJson(cleaned);
        if (pretty != null) return pretty;

        return ManualIndent(trimmed);
    }

    private static string? TryParseJson(string text)
    {
        try
        {
            var options = new System.Text.Json.JsonDocumentOptions
            {
                AllowTrailingCommas = true,
                CommentHandling = System.Text.Json.JsonCommentHandling.Skip
            };
            using var doc = System.Text.Json.JsonDocument.Parse(text, options);
            return System.Text.Json.JsonSerializer.Serialize(
                doc.RootElement,
                new System.Text.Json.JsonSerializerOptions { WriteIndented = true });
        }
        catch
        {
            return null;
        }
    }

    private static string ManualIndent(string text)
    {
        var sb     = new StringBuilder();
        int indent = 0;
        bool inStr = false;

        foreach (char ch in text)
        {
            if (ch == '"' && (sb.Length == 0 || sb[^1] != '\\'))
                inStr = !inStr;

            if (inStr)
            {
                sb.Append(ch);
                continue;
            }

            switch (ch)
            {
                case '{' or '[':
                    sb.Append(ch);
                    sb.AppendLine();
                    sb.Append(new string(' ', ++indent * 2));
                    break;
                case '}' or ']':
                    sb.AppendLine();
                    sb.Append(new string(' ', --indent * 2));
                    sb.Append(ch);
                    break;
                case ',':
                    sb.Append(ch);
                    sb.AppendLine();
                    sb.Append(new string(' ', indent * 2));
                    break;
                case ':':
                    sb.Append(": ");
                    break;
                default:
                    if (!(ch == ' ' && sb.Length > 0 && sb[^1] == ' '))
                        sb.Append(ch);
                    break;
            }
        }

        return sb.ToString().Trim();
    }

    // ─── JSON-to-markdown conversion (fallback safety net) ───────────────────────

    /// <summary>
    /// Returns true only when <paramref name="text"/> is syntactically valid JSON
    /// (i.e. actually parseable — not just any string that starts with '{').
    /// </summary>
    private static bool IsActualJson(string text)
    {
        if (string.IsNullOrWhiteSpace(text)) return false;
        var t = text.Trim();
        if ((!t.StartsWith("{") || !t.EndsWith("}")) &&
            (!t.StartsWith("[") || !t.EndsWith("]")))
            return false;
        return TryParseJson(t) != null;
    }

    /// <summary>
    /// Converts an <see cref="AnalysisResult"/>-shaped JSON object into readable markdown
    /// prose so that the PDF renders human-readable sections instead of raw JSON code.
    /// </summary>
    private static string ConvertJsonToMarkdown(string json)
    {
        try
        {
            var opts = new System.Text.Json.JsonDocumentOptions
            {
                AllowTrailingCommas = true,
                CommentHandling     = System.Text.Json.JsonCommentHandling.Skip
            };
            using var doc = System.Text.Json.JsonDocument.Parse(json, opts);

            if (doc.RootElement.ValueKind != System.Text.Json.JsonValueKind.Object)
                return json;

            var sb = new StringBuilder();

            foreach (var prop in doc.RootElement.EnumerateObject())
            {
                switch (prop.Value.ValueKind)
                {
                    case System.Text.Json.JsonValueKind.String:
                        var str = prop.Value.GetString();
                        if (!string.IsNullOrWhiteSpace(str))
                        {
                            sb.AppendLine($"## {CamelCaseToTitle(prop.Name)}");
                            sb.AppendLine(str);
                            sb.AppendLine();
                        }
                        break;

                    case System.Text.Json.JsonValueKind.Array:
                        var arrItems = prop.Value.EnumerateArray().ToList();
                        if (arrItems.Count == 0) break;

                        sb.AppendLine($"## {CamelCaseToTitle(prop.Name)}");
                        foreach (var item in arrItems)
                        {
                            if (item.ValueKind == System.Text.Json.JsonValueKind.String)
                            {
                                sb.AppendLine($"- {item.GetString()}");
                            }
                            else if (item.ValueKind == System.Text.Json.JsonValueKind.Object)
                            {
                                if (item.TryGetProperty("name", out var nameProp))
                                    sb.AppendLine($"### {nameProp.GetString()}");
                                if (item.TryGetProperty("description", out var descProp))
                                    sb.AppendLine(descProp.GetString());
                                if (item.TryGetProperty("usageExample", out var exProp))
                                    sb.AppendLine($"*Example:* {exProp.GetString()}");
                                if (item.TryGetProperty("method", out var methProp) &&
                                    item.TryGetProperty("path",   out var pathProp))
                                    sb.AppendLine($"**{methProp.GetString()?.ToUpper()} {pathProp.GetString()}**");
                                if (item.TryGetProperty("description", out var epDesc))
                                    sb.AppendLine(epDesc.GetString());
                                sb.AppendLine();
                            }
                        }
                        sb.AppendLine();
                        break;
                }
            }

            return sb.ToString().Trim();
        }
        catch
        {
            return json; // Conversion failed — return original and let the renderer handle it
        }
    }

    private static string CamelCaseToTitle(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        var spaced = Regex.Replace(name, @"(?<=[a-z])(?=[A-Z])", " ");
        return char.ToUpper(spaced[0]) + spaced[1..];
    }

    // ─── Helpers ─────────────────────────────────────────────────────────────────

    private static string GetDocumentTitle(DocumentationType docType) => docType switch
    {
        DocumentationType.UserGuide            => "User Guide",
        DocumentationType.ApiDocumentation     => "API Documentation",
        DocumentationType.ArchitectureOverview => "Architecture Overview",
        DocumentationType.TechnicalDocumentation => "Technical Documentation",
        _                                      => "Full Documentation"
    };

    private static string GetMethodColor(string method) => method.ToUpperInvariant() switch
    {
        "GET"    => "#27AE60",
        "POST"   => "#2980B9",
        "PUT"    => "#F39C12",
        "PATCH"  => "#8E44AD",
        "DELETE" => "#E74C3C",
        _        => "#7F8C8D"
    };
}
